

export const DEFAULT_IMAGEN_PROMPT = `
You are a professional graphic designer compositing TWO images:

- Image 1 → SOURCE PERSON
- Image 2 → TARGET POSTER

PRIMARY OBJECTIVE:
Convert the person into a colored-pencil-sketched caricature and integrate them
into the poster WITHOUT overlapping ANY existing elements.

--------------------------------------------------
STEP 1: PERSON TRANSFORMATION
--------------------------------------------------

- Extract FULL PERSON (head → hands fully visible)
- Preserve EXACT pose, gesture, and proportions
- Style: 70% realistic + 30% caricature
- Transparent background ONLY

--------------------------------------------------
STEP 2: SAFE LAYOUT ANALYSIS (CRITICAL)
--------------------------------------------------

Before placing the subject, ANALYZE Image 2 and DEFINE:

1. HARD EXCLUSION ZONES (DO NOT TOUCH):
   - Top header (logos row)
   - All Malayalam headings (top-left & top-right)
   - Right-side text block
   - Bottom-right illustration (bird + laptop)

2. SAFE ZONE (ONLY AREA ALLOWED):
   - Central empty visual region between:
     * Below header
     * Left of right-side text
     * Above bottom illustration
   - Treat this as a BOUNDING BOX

--------------------------------------------------
STEP 3: FITTING LOGIC (MOST IMPORTANT)
--------------------------------------------------

You MUST ensure the subject fits INSIDE the SAFE ZONE bounding box.

STRICT RULES:

1. BOUNDING BOX FIT:
   - Compute full subject silhouette INCLUDING:
     * Fingers
     * Elbows
     * Hair volume
   - Fit ENTIRE silhouette inside safe zone

2. AUTO SCALING:
   - Start at ~30% canvas width
   - IF any part crosses safe zone:
     → SCALE DOWN progressively until FULLY inside

3. CENTERING:
   - Horizontally center within SAFE ZONE
   - Vertically place at ~55% of SAFE ZONE height (not full canvas)

4. COLLISION DETECTION (MANDATORY):
   - Check intersections with:
     * Text blocks
     * Logos
     * Graphics
   - IF collision detected:
     → Reduce scale AND slightly shift within safe zone
     → NEVER allow overlap

--------------------------------------------------
STEP 4: EDGE BLENDING
--------------------------------------------------

- Soft feathered edges
- Slight fade at bottom
- NO white borders / glow / shadow blocks
- Poster texture must remain visible

--------------------------------------------------
FINAL NON-NEGOTIABLE RULES
--------------------------------------------------

- ZERO overlap with ANY poster element
- FULL subject must be visible (no cropping)
- NO background behind subject
- Maintain poster integrity completely

FAIL CONDITION:
If subject overlaps ANY element → RESULT IS INVALID

SUCCESS CONDITION:
Subject appears naturally embedded, centered, and perfectly contained
within the safe zone with clean spacing on all sides.
`;
export const generateCaricatureDirectly = async (base64Image, posterBase64, pushLog, customPrompt) => {
  const apiKey = import.meta.env.VITE_GEMINI_API_KEY;
  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image:generateContent?key=${apiKey}`;
  
  // Remove data:image/*;base64, prefix from both images
  const base64Data = base64Image.split(',')[1];
  const mimeType = base64Image.split(';')[0].split(':')[1];
  
  const posterBase64Data = posterBase64.split(',')[1];
  const posterMimeType = posterBase64.split(';')[0].split(':')[1];

  const requestBody = {
    contents: [{
      parts: [
        { text: customPrompt },
        {
          inlineData: {
            mimeType: mimeType,
            data: base64Data
          }
        },
        {
          inlineData: {
            mimeType: posterMimeType,
            data: posterBase64Data
          }
        }
      ]
    }],
    generationConfig: {
      temperature: 0.7
    }
  };

  pushLog({ endpoint: 'gemini-2.5-flash-image', request: requestBody });

  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(requestBody)
  });

  const data = await response.json();
  pushLog({ endpoint: 'gemini-2.5-flash-image (Response)', response: data });

  if (data.error) {
    throw new Error(data.error.message);
  }

  // Extract base64 image from response
  if (data.candidates && data.candidates.length > 0) {
    const imagePart = data.candidates[0].content.parts.find(part => part.inlineData);
    if (imagePart && imagePart.inlineData) {
      const mimeType = imagePart.inlineData.mimeType || 'image/png';
      return `data:${mimeType};base64,${imagePart.inlineData.data}`;
    } else {
      throw new Error("No image generated by the API.");
    }
  } else {
    throw new Error("No candidates in response from the API.");
  }
};
