
export const DEFAULT_IMAGEN_PROMPT = "Act as a graphic designer. Create a composite image by placing a vibrant, colorful pencil-sketch caricature of the person from [Image 1] onto the center of the voting poster in [Image 2].Technical Requirements: > 1. Match Framing: The caricature must use the same body-crop as the source photo (e.g., if the source is a headshot, the caricature is a headshot).2. Seamless Integration: The subject must blend into the background of the poster without any borders, frames, or outlines.3. Preserve Template: Do not alter, blur, or hallucinate the existing text, logos, or background details of the poster template.4. Style: High-contrast, sharp pencil lines, saturated colors, professional caricature exaggeration."

export const generateCaricatureDirectly = async (base64Image, posterBase64, pushLog, customPrompt) => {
  const apiKey = import.meta.env.VITE_GEMINI_API_KEY;
  const url = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-image:generateContent?key=${apiKey}`;
  
  // Remove data:image/*;base64, prefix from both images
  const base64Data = base64Image.split(',')[1];
  const mimeType = base64Image.split(';')[0].split(':')[1];
  
  const posterBase64Data = posterBase64.split(',')[1];
  const posterMimeType = posterBase64.split(';')[0].split(':')[1];

  const requestBody = {
    contents: [{
      parts: [
        { text: customPrompt },
        {
          inlineData: {
            mimeType: mimeType,
            data: base64Data
          }
        },
        {
          inlineData: {
            mimeType: posterMimeType,
            data: posterBase64Data
          }
        }
      ]
    }],
    generationConfig: {
      temperature: 0.7
    }
  };

  pushLog({ endpoint: 'gemini-2.5-flash-image', request: requestBody });

  const response = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(requestBody)
  });

  const data = await response.json();
  pushLog({ endpoint: 'gemini-2.5-flash-image (Response)', response: data });

  if (data.error) {
    throw new Error(data.error.message);
  }

  // Extract base64 image from response
  if (data.candidates && data.candidates.length > 0) {
    const imagePart = data.candidates[0].content.parts.find(part => part.inlineData);
    if (imagePart && imagePart.inlineData) {
      const mimeType = imagePart.inlineData.mimeType || 'image/png';
      return `data:${mimeType};base64,${imagePart.inlineData.data}`;
    } else {
      throw new Error("No image generated by the API.");
    }
  } else {
    throw new Error("No candidates in response from the API.");
  }
};
